spring.application.name=codebase-assistant

# Server port
server.port=8080

# Neon PostgreSQL DataSource Configuration
spring.datasource.url=jdbc:postgresql://ep-misty-hat-b3kcvwdq-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring AI - Base Google Gemini Configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.project-id=codebase-assistant

# Spring AI - Explicit Embedding Configuration (Required to fix the startup crash)
spring.ai.google.genai.embedding.project-id=codebase-assistant
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}

# Spring AI - PgVector Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=true


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB